### ISSUE TITLE
Everything returns an empty list

### ISSUE THREAD

**Issue by nw0** [jxk20/nlb_goodreads_searcher#17]
Every GET /api?isbn=%221234567890234%22 returns 200 with an empty list `[]`, so I get no results in the table.

**Comment by nw0** [comment]
I still experience this error, with the following test file:

```
Book Id,Title,Author,Author l-f,Additional Authors,ISBN,ISBN13,My Rating,Average Rating,Publisher,Binding,Number of Pages,Year Published,Original Publication Year,Date Read,Date Added,Bookshelves,Bookshelves with positions,Exclusive Shelf,My Review,Spoiler,Private Notes,Read Count,Recommended For,Recommended By,Owned Copies,Original Purchase Date,Original Purchase Location,Condition,Condition Description,BCID
28502731,The Attention Merchants: The Epic Scramble to Get Inside Our Heads,Tim Wu,"Wu, Tim",,"=""0385352026""","=""9780385352024""",2,4.09,Knopf,ebook,384,2016,2016,2022/02/24,2019/09/02,,,read,,,,1,,,0,,,,,
265270,The Seven Last Words,Fulton J. Sheen,"Sheen, Fulton J.",,"=""0818907606""","=""9780818907609""",0,4.62,Saint Pauls/Alba House,Paperback,64,1996,1982,,2022/02/13,to-read,to-read (#194),to-read,,,,0,,,0,,,,,
338798,Ulysses,James Joyce,"Joyce, James","Morris L. Ernst, John M. Woolsey","=""""","=""""",0,3.74,Vintage,Paperback,783,1990,1922,,2022/02/13,to-read,to-read (#193),to-read,,,,0,,,0,,,,,
30933,Brideshead Revisited,Evelyn Waugh,"Waugh, Evelyn",,"=""0316926345""","=""9780316926348""",0,4.00,Back Bay Books,Paperback,351,1982,1945,,2022/02/13,to-read,to-read (#192),to-read,,,,0,,,0,,,,,
```

The last 3 rows are `to-read`, and I get two HTTP GET requests (*Ulysses* has no ISBN):

```
https://nlb-goodreads-searcher.herokuapp.com/api?isbn=9780818907609
https://nlb-goodreads-searcher.herokuapp.com/api?isbn=9780316926348
```

both returning `[]`.

The only row in the resulting table is for *Ulysses*.

**Comment by jxk20** [comment]
> 

This should be the expected response. NLB does not seem to stock these two editions of these books. 

For _Brideshead Revisted_: NLB only has the editions for ISBNs 9780241472736 and 9780241951613 available. Navigate to  https://search.nlb.gov.sg/onesearch/Search?query=Brideshead%20revisited&Type=Book, for each of the 1st two results, click "See more" to view the available ISBN13. 

Additionally, I don't think  _The Seven Last Words_ is available in NLB (See https://search.nlb.gov.sg/onesearch/Search?query=%22the%20Seven%20Last%20Words%22&Type=Book)
