### ISSUE TITLE
Only search "to-read" books?

### ISSUE THREAD

**Issue by nw0** [jxk20/nlb_goodreads_searcher#18]
I selected my Goodreads CSV with 647 rows. It seems a little excessive to search for all my "read" books, since I've already read them. Perhaps it would be more relevant to:

- Search only "to-read" books; or
- Provide an option to select which books to search for; or
- List all the books, but only search for "read" books on demand?

**Comment by jxk20** [comment]
https://github.com/jxk20/nlb_goodreads_searcher/pull/19 will only search for "to-read" books.
